FROM nvidia/cuda:11.2.2-cudnn8-devel-ubuntu18.04

RUN apt update -y
RUN apt upgrade -y

RUN apt install -y tesseract-ocr
RUN apt install -y libtesseract-dev

RUN apt install -y git
RUN apt install -y python3
RUN apt install -y python3-pip
RUN pip3 install pkgconfig
RUN apt install -y pkg-config
RUN pip3 install 'git+https://github.com/facebookresearch/fvcore'
RUN pip3 install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip3 install 'git+https://github.com/facebookresearch/detectron2.git'

RUN apt install -y ffmpeg
COPY ./requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt

COPY ./src /src
RUN echo "USE_CPU=False" >> /src/config.py

ENTRYPOINT ["python3", "/src/main.py"]