version: '3.7'

services:
  segmentation_api:
    build: 
      context: .
      dockerfile: "Dockerfile_GPU"
    ports:
      - '8000:8000'
    restart: on-failure
    command: pytest /src
    runtime: nvidia